for review
DmitriyPodkovko/IP-decoding pull request #1
Opened 2022-12-08 13:29 UTC by DmitriyPodkovko

2022-12-14 12:35 UTC, DmitriyPodkovko commented
Файли main_draft.py та via_socket_module.py не потребують уваги - це мої початкові наброски, залишав собі шпаргалки для копі-паст в роботі на майбутнє

2022-12-15 21:06 UTC, scand1ce requested changes

2022-12-15 21:06 UTC, scand1ce commented on const/constants.py
> +QUERIES = dict(
`QUERIES` должны лежать в queries.py, отдельно от констант

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +from const.constants import (IPINFO_URL, ITERATOR_TOKENS,
лучше сделать `from const import constants as c ` и потом брать то что тебе нужно `c.IPINFO_URL` прям в коде

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +        token = next(ITERATOR_TOKENS, '-1')
токены лучше получать из внешнего сервиса если это возможно, если нет из БД, а если и это не вариант, то в константах токены нужно выгружать из .env файла списком и лоудить джейсоном

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +def get_response(url, ip_address, token):
это нужно вынести в helpers/sender.py и юзать унифицировано для всех запросов, урл нужно билдить перед тем как ты его передаешь в функцию

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +            result = (f"{response.json()['city'] if 'city' in response.json() else 'No City'}, "
подумай, возможно можно сделать функцию и поместить ее в /helpers/results.py, которая будет принимать параметрами все то что ты делаешь много раз + response.json() нужно обработать через try/except, может вывалить ошибку, если вернет не то что нужно и поместить в переменную

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +def handler(input_file, delimiter, url, token, output_file_all_ip, output_file_ukr_ip, output_file_ukr_mobile_ip):
вынести в handlers/что_делает.py (думаю ты поймешь о чем речь)

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +            with connect(DB_NAME) as conn:
здесь не должно быть коннекта к БД, это должен быть класс, который полностью отвечает за работу с БД и ожидает в конструкторе все данные для коннекта, а запросы ожидают параметры запроса, поместить в /database/db.py, в эту же директорию помести queries.py

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +                for ip in range(0, len(ip_list)):
почему по индексам получаешь элемент списка, а не берешь элемент на каждой итерации из list_ip, `for ip in list_ip:`

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +                    if ip_list[ip] is not nan:
валидаторы помогут избежать проверки

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +                        if str(ip_list[ip]).strip():
не понятно что ты пытаешься здесь сделать и зачем, по коду, ясно конечно, но в целом я бы это переделал

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +                                db_update_at = datetime.strptime(row[4], '%Y-%m-%d %H:%M:%S')
все манипуляции с данными по преобразованию, должны производится при сериализации/десиреализации

2022-12-15 21:06 UTC, scand1ce commented on main.py
> +        df.to_csv(output_file_all_ip, sep=delimiter, index=True, header=True, encoding='utf-8-sig')
чтение из файла и запись в файл, должны выполнять хелперы типа reader.py/writer.py

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +            for ip in ls:
есть вариант запписывать сразу пачкой данные в .csv, подумай над этим)

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +def get_ip_list_from_file(file_name):
это тоже редер, который должен ожидать параметром, имя файла

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +            with open('unable_to_resolve.txt', 'w') as ex_file_429:
это лютое решение) нужно переделать + имена параметров не айс + отсутствие докстринго и ретайпхинтингов, ты через пару тройку недель будешь смотреть на этот код, вроде не ты его писал, а так будет легче разобраться что к чему

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +                        #     'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15',
если комменты не юзаются, удали их или напиши `# TODO:  somthing`

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +                        user_agent_list = [
есть либа которая генерит в одну строчку юзерагентов

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +                        proxies = {
хардкод, спрятать в .env

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +
много мусора, который решиться валидаторами

2022-12-15 21:06 UTC, scand1ce commented on main_draft.py
> +if __name__ == '__main__':
здесь должны вызываться только функции, имена файлов это константы, я бы вообще сделал чекер директории, который будет искать файл по формату, а после полной обработки, удалять его или перемещать в директорию в done/

2022-12-15 21:06 UTC, scand1ce commented on via_socket_module.py
> +# Decoding IP address to domain name from excel using socket module
Этот файл не юзается на сколько я понимаю, если нет, его нужно удалить, а код можешь поместить в gists для своего аккаунта

2023-02-13 13:25 UTC, DmitriyPodkovko commented on via_socket_module.py
> +# Decoding IP address to domain name from excel using socket module
+ (move to gists)

2023-02-13 13:25 UTC, DmitriyPodkovko commented on main_draft.py
> +if __name__ == '__main__':
/+ (move to gists)

2023-02-13 13:26 UTC, DmitriyPodkovko commented on main_draft.py
> +
++ (move to gists)

2023-02-13 13:27 UTC, DmitriyPodkovko commented on main_draft.py
> +                        proxies = {
++ (move to gists)

2023-02-13 13:27 UTC, DmitriyPodkovko commented on main_draft.py
> +                        user_agent_list = [
++ (move to gists)

2023-02-14 12:21 UTC, DmitriyPodkovko commented on const/constants.py
> +QUERIES = dict(
++ (move to db/queries.py)

2023-02-14 12:21 UTC, DmitriyPodkovko commented on main.py
> +from const.constants import (IPINFO_URL, ITERATOR_TOKENS,
++

2023-02-14 12:26 UTC, DmitriyPodkovko commented on main.py
> +        token = next(ITERATOR_TOKENS, '-1')
-- (code is increase, is not in this case)

2023-02-14 13:12 UTC, DmitriyPodkovko commented on main.py
> +def get_response(url, ip_address, token):
--

2023-02-14 13:12 UTC, DmitriyPodkovko commented on main.py
> +            result = (f"{response.json()['city'] if 'city' in response.json() else 'No City'}, "
--

2023-02-20 20:56 UTC, merged